# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 754c8e3310b55c1ffd2a998636d8f04a989f1e164c9d6402443fce1b749e74232e06b46a45db397ec62ab014e498b3525e4b6727ad2d1ee4438c47b76cd588cb

test:
  secret_key_base: 075c37ccf5c60fef1dc93dcff2d4c8ecce0995e0f52e51ce72a6cb77a6a148c66e305483fb607fd17d3e5f0bf50ac7351932b7ad282dee38b931c0f816451e00

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
